#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi

#
# Editors
#
export ALTERNATE_EDITOR=""
export EDITOR="nvim"                  # $EDITOR opens in terminal
# export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
# export VISUAL="kitty nvim"         # $VISUAL opens in GUI mode
export PAGER='less'
export TERM='screen-256color'
#
# Language
#

if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
    /usr/local/{bin,sbin}
    $HOME/.local/bin
    $HOME/.emacs.d/bin
    $HOME/go/bin
    $path
    /opt/homebrew/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -z-4'
export XAUTHORITY=~/.Xauthority
WINDOWS=/mnt/c/Windows
if [ -d "$WINDOWS" ] ; then
    # export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
    # MobaXterm
    export DISPLAY=192.168.0.198:0.0
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

##
# Your previous /Users/khadd/.zprofile file was backed up as /Users/khadd/.zprofile.macports-saved_2024-05-22_at_21:45:24
##

# MacPorts Installer addition on 2024-05-22_at_21:45:24: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2024-05-22_at_21:45:24: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

