package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?/init.lua"
package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?.lua"

return {

  {
    -- "3rd/image.nvim",
    -- opts = {
    --   -- backend = "ueberzug",
    --   backend = "kitty",
    -- },
    -- integrations = {
    --   markdown = {
    --     enabled = true,
    --     clear_in_insert_mode = true,
    --     download_remote_images = true,
    --     only_render_image_at_cursor = false,
    --     filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
    --   },
    -- },
  },
  -- {
  --   "vhyrro/luarocks.nvim",
  --   priority = 1001, -- this plugin needs to run before anything else
  --   opts = {
  --     rocks = { "magick" },
  --   },
  -- },
  -- {
  --   "3rd/image.nvim",
  --   event = "VeryLazy",
  --   dependencies = {
  --     { "luarocks.nvim" },
  --     {
  --       "nvim-treesitter/nvim-treesitter",
  --       build = ":TSUpdate",
  --       config = function()
  --         require("nvim-treesitter.configs").setup({
  --           ensure_installed = { "markdown" },
  --           highlight = { enable = true },
  --         })
  --       end,
  --     },
  --   },
  --   opts = {
  --     backend = "kitty",
  --     integrations = {
  --       markdown = {
  --         enabled = true,
  --         clear_in_insert_mode = false,
  --         download_remote_images = true,
  --         only_render_image_at_cursor = false,
  --         filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
  --       },
  --       neorg = {
  --         enabled = true,
  --         clear_in_insert_mode = false,
  --         download_remote_images = true,
  --         only_render_image_at_cursor = false,
  --         filetypes = { "norg" },
  --       },
  --     },
  --     max_width = nil,
  --     max_height = nil,
  --     max_width_window_percentage = nil,
  --     max_height_window_percentage = 50,
  --     kitty_method = "normal",
  --   },
  -- },
  -- {
  -- Display image within terminal, useful for markdown notes
  -- event = "VeryLazy",
  -- "lucasdf/hologram.nvim",
  -- branch = "get-extmarks-error-handler",
  -- config = function()
  --   require("hologram").setup({
  --     auto_display = false, -- WIP automatic markdown image display, may be prone to breaking
  --   })
  -- end,
  -- },
}
